### ISSUE TITLE
No method matching setindex!(::Mongoc.BSON, ::Nothing, ::String)

### ISSUE THREAD

**Issue by shivchawla** [felipenoris/Mongoc.jl#18]
`a = Mongoc.BSON(Dict("a" => nothing))`

throws an error

`ERROR: MethodError: no method matching setindex!(::Mongoc.BSON, ::Nothing, ::String)`

I guess this function should be added, right?

Thanks

**Comment by felipenoris** [comment]
Good catch!

I took a look at BSON specs, it defines a `null` value. I guess it will be better mapped to `missing` in julia. So I just pushed a patch on branch `fn/null` with this:

```julia
julia> using Mongoc

julia> doc = Mongoc.BSON(Dict( "a" => missing ))
BSON("{ "a" : null }")

julia> ismissing(doc["a"])
true

julia> doc["a"]
missing
```

Since there's no distinction in BSON specs between `nothing` and `missing`, I have to choose one of those to use when mapping to Julia.

What do you think?

**Comment by felipenoris** [comment]
Btw, with this solution, `Mongoc.BSON(Dict("a" => nothing))` will also throw an error. You just have to use a `missing` value instead of `nothing`.

**Comment by felipenoris** [comment]
Now I'm thinking maybe I should just use `nothing`. This will make comparing two documents consistent.

**Comment by shivchawla** [comment]
Thanks for fixing this!!
