### ISSUE TITLE
Windows 7 x64 issue

### ISSUE THREAD

**Issue by ivborissov** [felipenoris/Mongoc.jl#51]
Hi,
I have the following error when I try to install `Mongoc` on Windows 7 x64
```
  Building Mongoc → `C:\Julia\packages\Mongoc\lc4t6\deps\build.log`
┌ Error: Error building `Mongoc`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privilege
s
│ └ @ Base.Filesystem file.jl:794
│ [ Info: Directory C:\Julia\packages\Mongoc\lc4t6\deps\usr\bin does not exist!
│ ┌ Warning: Could not extract the platform key of https://github.com/felipenori
s/mongo-c-driver-builder/releases/download/v1.14.0_1/mongo-c-driver-builder.v1.1
4.0.x86_64-windows.tar.gz; continuing...
│ └ @ BinaryProvider C:\Julia\packages\BinaryProvider\TcAwt\src\Prefix.jl:185
│ [ Info: Downloading https://github.com/felipenoris/mongo-c-driver-builder/rele
ases/download/v1.14.0_1/mongo-c-driver-builder.v1.14.0.x86_64-windows.tar.gz to
C:\Julia\packages\Mongoc\lc4t6\deps\usr\downloads\mongo-c-driver-builder.v1.14.0
.x86_64-windows.tar.gz...
│ [ Info: No hash cache found
│ [ Info: Calculated hash 04b5eb428568797545136f6a4a07af4c0f00235d0a6182042e5eb2
1e562dbaeb for file C:\Julia\packages\Mongoc\lc4t6\deps\usr\downloads\mongo-c-dr
iver-builder.v1.14.0.x86_64-windows.tar.gz
│ [ Info: Installing C:\Julia\packages\Mongoc\lc4t6\deps\usr\downloads\mongo-c-d
river-builder.v1.14.0.x86_64-windows.tar.gz into C:\Julia\packages\Mongoc\lc4t6\
deps\usr
│ [ Info: Found a valid dl path concrt140.dll while looking for libmongoc
│ [ Info: Found a valid dl path libbson-1.0.dll while looking for libmongoc
│ [ Info: Found a valid dl path libmongoc-1.0.dll while looking for libmongoc
│ [ Info: C:\Julia\packages\Mongoc\lc4t6\deps\usr\bin\libmongoc-1.0.dll matches
our search criteria of libmongoc
│ [ Info: C:\Julia\packages\Mongoc\lc4t6\deps\usr\bin\libmongoc-1.0.dll cannot b
e dlopen'ed
│ [ Info: Found a valid dl path msvcp140.dll while looking for libmongoc
│ [ Info: Found a valid dl path vcruntime140.dll while looking for libmongoc
│ [ Info: Could not locate libmongoc inside C:\Julia\packages\Mongoc\lc4t6\deps\
usr\bin
│ ERROR: LoadError: LibraryProduct(nothing, ["libmongoc"], :libmongoc, "Prefix(C
:\\Julia\\packages\\Mongoc\\lc4t6\\deps\\usr)") is not satisfied, cannot generat
e deps.jl!
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #write_deps_file#156(::Bool, ::Function, ::String, ::Array{LibraryProduct
,1}) at C:\Julia\packages\BinaryProvider\TcAwt\src\Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple
{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryP
roduct,1}) at .\none:0
│  [4] top-level scope at none:0
│  [5] include at .\boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:403
│  [9] top-level scope at none:0
│ in expression starting at C:\Julia\packages\Mongoc\lc4t6\deps\build.jl:50
```
So dlls are build in `/usr/bin` but `deps.jl` is not created

**Comment by ivborissov** [comment]
I have coppied old `deps.jl` file:
```
if isdefined((@static VERSION < v"0.7.0-DEV.484" ? current_module() : @__MODULE__), :Compat)
    import Compat.Libdl
elseif VERSION >= v"0.7.0-DEV.3382"
    import Libdl
end
const libbson = "C:\\Julia\\packages\\Mongoc\\lc4t6\\deps\\usr\\bin\\libbson-1.0.dll"
const libmongoc = "C:\\Julia\\packages\\Mongoc\\lc4t6\\deps\\usr\\bin\\libmongoc-1.0.dll"
function check_deps()
    global libbson
    if !isfile(libbson)
        error("$(libbson) does not exist, Please re-run Pkg.build(\"rGrHf\"), and restart Julia.")
    end

    if Libdl.dlopen_e(libbson) in (C_NULL, nothing)
        error("$(libbson) cannot be opened, Please re-run Pkg.build(\"rGrHf\"), and restart Julia.")
    end

    global libmongoc
    if !isfile(libmongoc)
        error("$(libmongoc) does not exist, Please re-run Pkg.build(\"rGrHf\"), and restart Julia.")
    end

    if Libdl.dlopen_e(libmongoc) in (C_NULL, nothing)
        error("$(libmongoc) cannot be opened, Please re-run Pkg.build(\"rGrHf\"), and restart Julia.")
    end

end
```

But `using Mongoc` leads to:
```
[ Info: Precompiling Mongoc [4fe8b98c-fc19-5c23-8ec2-168ff83495f2]
ERROR: InitError: error compiling __init__: could not load library "C:\Julia\packages\Mongoc\lc4t6\deps\usr\bin\libmongoc-1.0.dll"
The specified module could not be found.

Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:633
 [2] _require_from_serialized(::String) at .\loading.jl:684
 [3] _require(::Base.PkgId) at .\loading.jl:967
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853
during initialization of module Mongoc
```

**Comment by ivborissov** [comment]
Sorry, my bad. After installing VS components `Libdl.open` started to work fine

**Comment by waqasahmad531** [comment]
> Sorry, my bad. After installing VS components `Libdl.open` started to work fine

Can you explain what exactly you did to make it work? I am trying to install Mongoc in windows 10 but am getting the same warnings and errors.

**Comment by ivborissov** [comment]
I think now `Mongoc.jl` supports Windows "out-of-the box", but when I configured it I compiled the dlls and manually copied the `deps.jl` file. I don't remember what VS components exactly I had to install but after I had VisualStudio Express installed the error was gone.

**Comment by waqasahmad531** [comment]
> I think now `Mongoc.jl` supports Windows "out-of-the box", but when I configured it I compiled the dlls and manually copied the `deps.jl` file. I don't remember what VS components exactly I had to install but after I had VisualStudio Express installed the error was gone.

Well I have been unsuccessful so far. I got following information from the build file: 
[ Info: Found a valid dl path concrt140.dll while looking for libmongoc
[ Info: Found a valid dl path libbson-1.0.dll while looking for libmongoc
[ Info: Found a valid dl path libmongoc-1.0.dll while looking for libmongoc
[ Info: C:\Users\waqas\.julia\packages\Mongoc\OxMdy\deps\usr\bin\libmongoc-1.0.dll matches our search criteria of libmongoc
[ Info: C:\Users\waqas\.julia\packages\Mongoc\OxMdy\deps\usr\bin\libmongoc-1.0.dll cannot be dlopen'ed
[ Info: Found a valid dl path msvcp140.dll while looking for libmongoc
[ Info: Found a valid dl path vcruntime140.dll while looking for libmongoc
[ Info: Could not locate libmongoc inside C:\Users\waqas\.julia\packages\Mongoc\OxMdy\deps\usr\bin
┌ Warning: Could not extract the platform key of https://github.com/felipenoris/mongo-c-driver-builder/releases/download/v1.14.0_1/mongo-c-driver-builder.v1.14.0.x86_64-windows.tar.gz; continuing...
└ @ BinaryProvider C:\Users\waqas\.julia\packages\BinaryProvider\kcGxO\src\Prefix.jl:185
[ Info: Destination file C:\Users\waqas\.julia\packages\Mongoc\OxMdy\deps\usr\downloads\mongo-c-driver-builder.v1.14.0.x86_64-windows.tar.gz already exists, verifying...
[ Info: Hash cache is consistent, returning true
[ Info: Installing C:\Users\waqas\.julia\packages\Mongoc\OxMdy\deps\usr\downloads\mongo-c-driver-builder.v1.14.0.x86_64-windows.tar.gz into C:\Users\waqas\.julia\packages\Mongoc\OxMdy\deps\usr
[ Info: Removing files installed by manifests\mongo-c-driver-builder.v1.14.0.x86_64-windows.list

Pkg.build("Mongoc") is not working because of dl open.

**Comment by ivborissov** [comment]
So, the problem is in `Libdl.dlopen` function? 
What do you get when you run the `Libdl.dlopen(...)` line from deps.jl?
Maybe it is worth to search for `Libdl` related issues
Or @felipenoris can be more helpful here )
